### ISSUE TITLE
Unpacked gem size is ~400Mb is that expected

### ISSUE THREAD

**Issue by CAMOBAP** [lutaml/xmi#30]
During investigation https://github.com/metanorma/metanorma-docker/issues/188 Ifound taht 

The size of `/usr/local/bundle/gems/xmi-0.3.0/references` is 381M

`docker run --rm metanorma/metanorma:1.10.1 du -sh /usr/local/bundle/gems/xmi-0.3.0/references`

381 MB looks too much, is that expected?

**Comment by ronaldtse** [comment]
Need to update gemspec to only include code.

**Comment by kwkwan** [comment]
The large size of this gem is mainly due to the files in reference folder.   Should we move these files into a new repo?

```
$ du -h ./xmi
8.0K	./xmi/bin
 34M	./xmi/references/ImplementationModels
347M	./xmi/references/ConceptualModels
381M	./xmi/references
...
416M	./xmi
```

**Comment by ronaldtse** [comment]
@kwkwan please update gemspec so it does not package non program files and test files.
