### ISSUE TITLE
Handling Enterprise Architect 15 exports (UML 2.4.1, UML 2.5)

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/xmi#35]
I have two exports of CityGML from Enterprise Architect 15:

<img width="512" alt="ea_export_options" src="https://github.com/lutaml/xmi/assets/11865/7bedca48-38d5-4b23-acc0-efb449fc76df">

* UML 2.4.1 (XMI 2.4.2) [full-242.xmi.zip](https://github.com/user-attachments/files/16171082/full-242.xmi.zip)
* UML 2.5 (XMI 2.5.1) [full-251.xmi.zip](https://github.com/user-attachments/files/16171083/full-251.xmi.zip)

Can we handle both of these export formats?

**Comment by kwkwan** [comment]
`UML 2.5 (XMI 2.5.1)` can be handled by the current version of xmi, but `UML 2.4.1 (XMI 2.4.2)` cannot be handled.  It is because namespaces of uml and xmi are old versions. (uml: "http://www.omg.org/spec/UML/20110701"  and xmi : "http://www.omg.org/spec/XMI/20110701").

**Comment by kwkwan** [comment]
Perhaps we may implement a mechanism to detect the namespaces and set the namespaces for Shale classes before parsing the xml file.

**Comment by ronaldtse** [comment]
I agree, can we try handling the UML 2.4.1 (XMI 2.4.2) version?

Maybe:
1. The user can configure this in the command, stating which version the EA / XMI / UML is
2. We can have an auto-detect function to check for version of EA / XMI / UML and load the correct classes.

In the future we will for sure run into this issue because EA will be updated and there will be new XMI / UML versions.
