### ISSUE TITLE
Unable to load XMI file from Enterprise Architect using "GML" MDG

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/xmi#38]
This model:
* https://github.com/metanorma/mn-samples-plateau/pull/114

Cannot be load by the `xmi` gem due to Enterprise Architect's GML MDG. We need to support loading of the file.

The model is at this location of the above PR (private model):
```
sources/001-mds/plateau_uml_20240708_all_packages_export.xmi
```

**Comment by kwkwan** [comment]
`GML` is supported by default in xmi v.0.3.6.  However, some classes such as `GML:DataType` or `GML:FeatureType` were missing as there was no such definition in previous xmi files.  New class definitions will be created according to the `sources/001-mds/plateau_uml_20240708_all_packages_export.xmi`.
