### ISSUE TITLE
Parse EA exported models encoded in Shift-JIS (not UTF-8)

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/xmi#51]
Enterprise Architect in different languages seem to produce different kinds of textual encoding.

In the PLATEAU 001 model, the client uses Japanese, and their EA exports in "Shift-JIS" encoding, which this gem currently fails to parse.

Reported by @ReesePlews:

> the client said that if the codeset of the .xmi was ShiftJIS lutaml seemed to give an error.
>
> if the codeset was windows1252 then luta correctly interpreted the .xmi file.
> 
> under "preferences" - "xml specifications" is the dialog where the codeset (codepage) is specified. on my win10 machine (japanese os but english menu settings with japanese locale) my "default" is windows1252
> 
![image](https://github.com/user-attachments/assets/2c2e44a8-7eb7-4a8d-8fa8-5d30f404e0af)
>
> i noticed from the client when they used shfitjis the kanji characters in the xmi file are correctly interpreted. in my .xmi file, the kanji are all HMTL hex entity encoded.

@ReesePlews is it possible to provide the Shift-JIS XMI file so we can test it? Thanks.

**Comment by ronaldtse** [comment]
Closing. Client indicated they can stick to UTF-8.

**Comment by ReesePlews** [comment]
thanks @ronaldtse when the time comes i believe the documentation should mention this.
